# Site settings
title: Sajay Sunny Mathew
email: sajay.mathew@anu.edu.au
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "sajaymathew.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
